version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: urbanflamebackend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER:   urban
      POSTGRES_PASSWORD: flame
      POSTGRES_DB:     urban_flame
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
